### ISSUE TITLE
Ya no funciona esto...

### ISSUE THREAD

**Issue by angeltonio** [danielpza/etecsa-cli#2]
De hecho la manera de instalarlo esta mal, asi como tambien los comandos ya no funcionan..

**Comment by angeltonio** [comment]
Me parece que hay que poner que no esta en el registro de npm y hay que instarlo manual

**Comment by danielpza** [comment]
sip, desde hace un tiempo no esta en los repositorios de npm, pero todavia funcionan los comandos, lo uso todos los dias. Te sugiero que lo descargues y lo compiles:

```sh
$ git clone https://github.com/danielpza/etecsa-cli.git
$ cd etecsa-cli
$ npm link
```

**Comment by danielpza** [comment]
Si te da algun error, puedes ponerlo aqui.

**Comment by davidpa9708** [comment]
@danielpza @angeltonio  el comando `npm-link` no funciona actualmente, hay un problema compilando `ts` por unos tipos que fallan, por unas dependencias que se updatearon. Ya se donde esta el error, es bastante simple, luego hago un PR para arreglar esto.

**Comment by danielpza** [comment]
@angeltonio, sincroniza los nuevos cambios en master, ya deberia estar bien.
