### ISSUE TITLE
Agregar otra funcionalidad

### ISSUE THREAD

**Issue by angeltonio** [danielpza/etecsa-cli#4]
Seria interesante poder ponerle una funcionalidad donde se le pase la cantidad de tiempo que quiero conectarme, tambien a veces cuando se le da al logout si se esta por ejemplo descargando algun fichero, deberia hacer el deslogueo forzado y da un error, tuve que ejecutar el comando otra vez para que desconectara..slds

**Comment by danielpza** [comment]
> Seria interesante poder ponerle una funcionalidad donde se le pase la cantidad de tiempo que quiero conectarme

**Comment by danielpza** [comment]
> Seria interesante poder ponerle una funcionalidad donde se le pase la cantidad de tiempo que quiero conectarme

Si estas en linux/macos es facil hacerlo con un comando, por ej para esperar 10 minutos antes de desconectar:

```sh
$ sleep 10m && etecsa logout
```

**Comment by danielpza** [comment]
> tambien a veces cuando se le da al logout si se esta por ejemplo descargando algun fichero

esto no me ha pasado, es probable que sea problema de etecsa o de la conexion en ese momento, se podria annadir una opcion para reintentar si falla.

**Comment by angeltonio** [comment]
> > Seria interesante poder ponerle una funcionalidad donde se le pase la cantidad de tiempo que quiero conectarme
> 
> Si estas en linux/macos es facil hacerlo con un comando, por ej para esperar 10 minutos antes de desconectar:
> 
> ```shell
> $ sleep 10m && etecsa logout
> ```

si pero seria interesante q la misma libreria lo gestionara y no el sistema operativo como tal..cierto??..porque si lo quiero hacer en windows ya es un problema..slds

**Comment by angeltonio** [comment]
> > tambien a veces cuando se le da al logout si se esta por ejemplo descargando algun fichero
> 
> esto no me ha pasado, es probable que sea problema de etecsa o de la conexion en ese momento, se podria annadir una opcion para reintentar si falla.

si seria intersante agregarle la funcionalidad..slds

**Comment by danielpza** [comment]
De la forma que esta ahora satisface mis necesidades por lo que no veo motivacion para annadir estos cambios, sin embargo eres bienvenido a hacer un PR :smiley:

**Comment by danielpza** [comment]
btw @angeltonio , la aplicacion esta de nuevo en npm, la puedes instalar con `npm i -g etecsa-cli`.

Sobre estos cambios, si planeamos hacerlo en un futuro pero ahora no es algo que apure (aparte de que no puedo probar la integracion con windows). Si seria bueno ver mas apoyo de parte de la comunidad con PRs y issues, recuerda que la aplicacion la estoy manteniendo en mi tiempo libre.

Saludos.

**Comment by danielpza** [comment]
Ninguna actividad por un tiempo, cerrando por mantenimiento.
